ICONS = {
    "note": "pen",
    "info": "info",
    "todo": "circle-check",
    "question": "circle-question-mark",
    "help": "circle-question-mark",
    "faq": "circle-question-mark",
    "warning": "circle-alert",
    "caution": "circle-alert",
    "attention": "circle-alert",
    "failure": "x",
    "fail": "x",
    "missing": "x",
    "danger": "zap",
    "error": "zap",
    "bug": "bug",
    "abstract": "clipboard-list",
    "summary": "clipboard-list",
    "tldr": "clipboard-list",
    "tip": "flame",
    "hint": "flame",
    "important": "flame",
    "success": "check",
    "check": "check",
    "done": "check",
    "example": "list",
    "quote": "quote",
    "cite": "quote",
    "others": "book-check",
}

CALLOUT_CSS = """<!-- Obsidian Callout Styles - Generated by Intaglio -->
<style>
  .callout {
    padding: 10px 24px 2px;
    margin: 1.5em 0;
    border-radius: 4px;
    --accent-rgb: 158, 158, 158;
    --accent-clr: rgb(var(--accent-rgb));
    background-color: rgba(var(--accent-rgb), 0.12);
  }

  .callout-icon {
    width: 1rem;
    margin-right: 0.5rem;
  }

  .callout-title {
    width: 80%;
    font-weight: bold;
    margin-bottom: 8px;
    display: flex;
    align-items: center;
    color: var(--accent-clr);
  }

  .callout-info,
  .callout-todo,
  .callout-note {
    --accent-rgb: 45, 122, 240;
  }

  .callout-abstract,
  .callout-summary,
  .callout-tldr,
  .callout-tip,
  .callout-hint,
  .callout-important {
    --accent-rgb: 0, 176, 174;
  }

  .callout-success,
  .callout-check,
  .callout-done {
    --accent-rgb: 32, 180, 85;
  }

  .callout-warning,
  .callout-question,
  .callout-help,
  .callout-faq,
  .callout-caution,
  .callout-attention {
    --accent-rgb: 233, 126, 35;
  }

  .callout-danger,
  .callout-error,
  .callout-bug,
  .callout-fail,
  .callout-failure,
  .callout-missing {
    --accent-rgb: 240, 62, 78;
  }

  .callout-example {
    --accent-rgb: 144, 104, 248;
  }

  .callout-quote,
  .callout-cite {
    --accent-rgb: 158, 158, 158;
  }

  details > summary:first-of-type::after {
    content: '▶';
    display: inline-block;
    position: relative;
    right: -1em;
    transition: transform 0.2s ease;
  }

  details[open] > summary:first-of-type::after {
    transform: rotate(90deg);
  }
</style>

<!-- Lucide CDN -->
<script src="https://unpkg.com/lucide@0.400.0/dist/umd/lucide.min.js"></script>
<script>
  lucide.createIcons({
    attrs: {
      'stroke-width': 2.5,
      stroke: 'currentColor',
    },
  });
</script>
"""
